name: ci-test

on:
  pull_request:
    branches:
      - main # 或者你用于主开发分支的其他名称
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run unit tests and collect coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Debug coverage files
        run: ls -R coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TD-gaowei/unit-test-react
          files: ./coverage/lcov.info # 修改为你实际的覆盖率报告路径
          fail_ci_if_error: true
          root_dir: /home/runner/work/unit-test-react/unit-test-react
          verbose: true
          flags: unittests
          # name: codecov-umbrella

      - name: Check PR
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          curl -v https://codecov.io/api/gh/${{ github.repository }}/commit/$COMMIT_SHA

          response=$(curl -s -L https://api.codecov.io/api/v2/github/TD-gaowei/repos/unit-test-react/report/sha=$COMMIT_SHA)

          echo "Codecov API Response: $response"

          coverage=$(echo "$response" | jq -r '.commit.totals.coverage')

          echo "Current coverage: $coverage"
